# Site
name: 'GlasgowCOPCollective'
description: 'The Glasgow COP Collective are a group of concerned citizens from a variety of backgrounds who
recognise the climate and ecological crises as the most significant threat of our time.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/COPwebsite'
#disqus: 'demowebsite'
email: 'cop26collective@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

intgov_spreadsheet_key: 2PACX-1vRJKHJ3k4dl3DxYOrf4dsg72DMaPEmRp-m-keuBS9Q-GPCHsNen2FRnhx2eg2gVNA

github_user: GlasgowCOP
github_repo: COPwebsite

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    David:
      name:           David
      site:           https://www.dharkness.co.uk
      avatar:         /assets/images/***.jpg
      bio:            "Hi I am David the web guy. I used Jekyll and the theme Mundana to create this site on GitHub Pages"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/175dh

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         /assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
